# Generated by Django 3.0.6 on 2020-06-27 21:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('milk', '0002_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=1024)),
                ('body', models.TextField()),
                ('path', models.CharField(db_index=True, max_length=1024, unique=True)),
                ('template', models.CharField(blank=True, default=None, max_length=1024, null=True)),
                ('published', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
